
rpc:
  client:
    # keeper服务
    "[datacenter.keeper.keeper]":
      plaintext: true
      enableKeepAlive: true
      keepAliveWithoutCalls: false
      keepAliveTime: 1000
      keepAliveTimeout: 1000
      idleTimeout: 60
      callTimeout: 3000
      subset: 30
      scheduler: true
      breaker:
        volumn: 100
        sleep: 1000
        errorRate: 50
        halfOpen: 10
    # shielder服务
    "[datacenter.shielder.shielder]":
      plaintext: true
      enableKeepAlive: true
      keepAliveWithoutCalls: false
      keepAliveTime: 1000
      keepAliveTimeout: 1000
      idleTimeout: 60
      callTimeout: 3000
      subset: 30
      scheduler: true
      breaker:
        volumn: 100
        sleep: 1000
        errorRate: 50
        halfOpen: 10